#!/bin/bash     
# Учебный скрипт для варификации пароля
# Описываем алгоритм введения пароля 

echo "Ввдите пароль (8 символов  A-Za-z0-9:)"
read -r  passwd 
#Запрашиваем у пользователя изменение 
echo Вы уверены что хотите изменить passwd, если ДА  нажмите [y] или любую кнопку для выхода  :

read -r reqwest 

check=$( echo "$reqwest" | grep "[Yy]" )

if	[[ "$?" == 0 ]]; then

	echo " Проверка passwd"  

else 
	echo "Неудачный пароль, повторите "
fi

echo "start checkin passwd $passwd" #после отладки удалить passwd в данной строке 

test=$(echo "$passwd" | grep -E '^[A-Za-z0-9!=\?@^%-<>\+_][^lO$#"\s]{8}+$')  # Дополнить регулярные выражения
	
	if [ "$?" == 0 ];
	then
	echo " Пароль успешно обновлен "
else
	echo "ERORR повторите ввод passwd еще раз"
	
	fi



